# Generated by Django 5.1.1 on 2024-09-23 09:51

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_cover_pages/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='artists_images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='debut_year',
            field=models.IntegerField(validators=[store.models.validate_year]),
        ),
    ]
