# Generated by Django 5.1.2 on 2024-10-16 09:46

import django.db.models.deletion
import review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('year_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('FTSY', 'Fantasy'), ('SCIFI', 'Science Fiction'), ('MYST_THRILL', 'Mystery/Thriller'), ('ROM', 'Romance'), ('HIST_FIC', 'Historical Fiction'), ('HORROR', 'Horror'), ('DYST', 'Dystopian'), ('ADVN', 'Adventure'), ('BIO_AUTOBIO', 'Biography/Autobiography'), ('SELF_HELP', 'Self Help'), ('HIST', 'History'), ('SCI', 'Science'), ('BSNS', 'Business')], default='MYST_THRILL', max_length=11)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to=review.models.book_cover_upload_to)),
                ('isbn', models.CharField(max_length=255)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[review.models.validate_rating])),
                ('added_on', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
