# Generated by Django 5.1.2 on 2024-10-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('DR', 'Drama'), ('CO', 'Comedy'), ('HO', 'Horror'), ('RO', 'Romance'), ('SF', 'Science Fiction'), ('FA', 'Fantasy'), ('DO', 'Documentary'), ('TH', 'Thriller')], default='AC', max_length=2)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
        ),
    ]
